#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GASB.Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PrimeNumber")]
	public partial class GASBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCLIENT(CLIENT instance);
    partial void UpdateCLIENT(CLIENT instance);
    partial void DeleteCLIENT(CLIENT instance);
    partial void InsertJOB(JOB instance);
    partial void UpdateJOB(JOB instance);
    partial void DeleteJOB(JOB instance);
    #endregion
		
		public GASBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PrimeNumberConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GASBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GASBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GASBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GASBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENT> CLIENTs
		{
			get
			{
				return this.GetTable<CLIENT>();
			}
		}
		
		public System.Data.Linq.Table<JOB> JOBs
		{
			get
			{
				return this.GetTable<JOB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENT")]
	public partial class CLIENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _CLIENT_ID;
		
		private string _E_MAIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCLIENT_IDChanging(System.Guid value);
    partial void OnCLIENT_IDChanged();
    partial void OnE_MAILChanging(string value);
    partial void OnE_MAILChanged();
    #endregion
		
		public CLIENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid CLIENT_ID
		{
			get
			{
				return this._CLIENT_ID;
			}
			set
			{
				if ((this._CLIENT_ID != value))
				{
					this.OnCLIENT_IDChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_ID = value;
					this.SendPropertyChanged("CLIENT_ID");
					this.OnCLIENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_MAIL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string E_MAIL
		{
			get
			{
				return this._E_MAIL;
			}
			set
			{
				if ((this._E_MAIL != value))
				{
					this.OnE_MAILChanging(value);
					this.SendPropertyChanging();
					this._E_MAIL = value;
					this.SendPropertyChanged("E_MAIL");
					this.OnE_MAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JOB")]
	public partial class JOB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _JOB_ID;
		
		private long _N;
		
		private System.Guid _CLIENT_ID;
		
		private System.DateTime _ASSIGN_DATE;
		
		private System.Nullable<bool> _RESULT;
		
		private System.Nullable<System.DateTime> _RESULT_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJOB_IDChanging(System.Guid value);
    partial void OnJOB_IDChanged();
    partial void OnNChanging(long value);
    partial void OnNChanged();
    partial void OnCLIENT_IDChanging(System.Guid value);
    partial void OnCLIENT_IDChanged();
    partial void OnASSIGN_DATEChanging(System.DateTime value);
    partial void OnASSIGN_DATEChanged();
    partial void OnRESULTChanging(System.Nullable<bool> value);
    partial void OnRESULTChanged();
    partial void OnRESULT_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnRESULT_DATEChanged();
    #endregion
		
		public JOB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid JOB_ID
		{
			get
			{
				return this._JOB_ID;
			}
			set
			{
				if ((this._JOB_ID != value))
				{
					this.OnJOB_IDChanging(value);
					this.SendPropertyChanging();
					this._JOB_ID = value;
					this.SendPropertyChanged("JOB_ID");
					this.OnJOB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N", DbType="BigInt NOT NULL")]
		public long N
		{
			get
			{
				return this._N;
			}
			set
			{
				if ((this._N != value))
				{
					this.OnNChanging(value);
					this.SendPropertyChanging();
					this._N = value;
					this.SendPropertyChanged("N");
					this.OnNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENT_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CLIENT_ID
		{
			get
			{
				return this._CLIENT_ID;
			}
			set
			{
				if ((this._CLIENT_ID != value))
				{
					this.OnCLIENT_IDChanging(value);
					this.SendPropertyChanging();
					this._CLIENT_ID = value;
					this.SendPropertyChanged("CLIENT_ID");
					this.OnCLIENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSIGN_DATE", DbType="SmallDateTime NOT NULL")]
		public System.DateTime ASSIGN_DATE
		{
			get
			{
				return this._ASSIGN_DATE;
			}
			set
			{
				if ((this._ASSIGN_DATE != value))
				{
					this.OnASSIGN_DATEChanging(value);
					this.SendPropertyChanging();
					this._ASSIGN_DATE = value;
					this.SendPropertyChanged("ASSIGN_DATE");
					this.OnASSIGN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESULT", DbType="Bit")]
		public System.Nullable<bool> RESULT
		{
			get
			{
				return this._RESULT;
			}
			set
			{
				if ((this._RESULT != value))
				{
					this.OnRESULTChanging(value);
					this.SendPropertyChanging();
					this._RESULT = value;
					this.SendPropertyChanged("RESULT");
					this.OnRESULTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESULT_DATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> RESULT_DATE
		{
			get
			{
				return this._RESULT_DATE;
			}
			set
			{
				if ((this._RESULT_DATE != value))
				{
					this.OnRESULT_DATEChanging(value);
					this.SendPropertyChanging();
					this._RESULT_DATE = value;
					this.SendPropertyChanged("RESULT_DATE");
					this.OnRESULT_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
