<?xml version="1.0" encoding="utf-8"?><Database Name="PrimeNumber" Class="GASBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=PrimeNumber;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PrimeNumberConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CLIENT" Member="CLIENTs">
    <Type Name="CLIENT">
      <Column Name="CLIENT_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_MAIL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.JOB" Member="JOBs">
    <Type Name="JOB">
      <Column Name="JOB_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="N" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CLIENT_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ASSIGN_DATE" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="RESULT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RESULT_DATE" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>